import React from 'react';
import {
  Utensils,
  ShoppingCart,
  Fuel,
  HeartPulse,
  Home,
  Zap,
  ShoppingBag,
  Film,
  GraduationCap,
  Plane,
  MoreHorizontal,
  Briefcase,
  TrendingUp,
  Laptop,
  DollarSign,
  Gift,
  PlusCircle,
  Wallet as WalletIcon,
  CreditCard,
  Building,
  Smartphone,
  Coins,
  Shield,
  PiggyBank,
  CheckCircle2,
  Calendar,
  AlertCircle,
  FileText,
  Clock,
  Sparkles,
  Award,
  Target,
  Car,
  Wifi,
  SmartphoneCharging,
  Droplet,
  Flame,
  HelpCircle
} from 'lucide-react';

export const ICON_MAP: Record<string, React.ComponentType<{ className?: string; size?: number }>> = {
  Utensils,
  ShoppingCart,
  Fuel,
  HeartPulse,
  Home,
  Zap,
  ShoppingBag,
  Film,
  GraduationCap,
  Plane,
  MoreHorizontal,
  Briefcase,
  TrendingUp,
  Laptop,
  DollarSign,
  Gift,
  PlusCircle,
  Wallet: WalletIcon,
  CreditCard,
  Building,
  Smartphone,
  Coins,
  Shield,
  PiggyBank,
  CheckCircle2,
  Calendar,
  AlertCircle,
  FileText,
  Clock,
  Sparkles,
  Award,
  Target,
  Car,
  Wifi,
  SmartphoneCharging,
  Droplet,
  Flame,
};

export function renderCategoryIcon(iconName: string, className = "w-5 h-5", size?: number) {
  const IconComponent = ICON_MAP[iconName] || HelpCircle;
  return <IconComponent className={className} size={size} />;
}
